import fs from "node:fs";
import path from "node:path";
import PDFDocument from "pdfkit";
import { prisma } from "../db";
import { drawBrandHeader, drawSectionLabel, drawTableHeader, drawTotalsBox, getDocumentBrand } from "./documentBrand";

function money(value: { toFixed(decimalPlaces: number): string } | string | number) {
  return `AED ${Number(value.toString()).toFixed(2)}`;
}

function drawCompanyBlock(doc: PDFKit.PDFDocument, brand: ReturnType<typeof getDocumentBrand>, label: string, company: { legalName: string; location: string; email: string; trn?: string | null }, x: number, y: number) {
  const width = 220;
  drawSectionLabel(doc, brand, label, x, y);
  const lines = [
    company.legalName,
    company.location,
    `Email: ${company.email}`,
    `TRN: ${company.trn ?? "Not set"}`,
  ];
  let cursorY = y + 32;
  doc.font("Helvetica").fontSize(9.5).fillColor(brand.text);
  for (const line of lines) {
    const lineHeight = doc.heightOfString(line, { width, lineGap: 1 });
    doc.text(line, x, cursorY, { width, lineGap: 1 });
    cursorY += lineHeight + 2;
  }
  return cursorY;
}

function drawBankDetails(doc: PDFKit.PDFDocument, brand: ReturnType<typeof getDocumentBrand>, company: {
  bankName?: string | null;
  bankBeneficiaryName?: string | null;
  bankAccountNumber?: string | null;
  bankIban?: string | null;
  bankCid?: string | null;
  bankBranch?: string | null;
}, x: number, y: number) {
  const rows = [
    ["Bank Name", company.bankName],
    ["Beneficiary", company.bankBeneficiaryName],
    ["Account No", company.bankAccountNumber],
    ["IBAN", company.bankIban],
    ["CID", company.bankCid],
    ["Branch", company.bankBranch],
  ].filter((row): row is [string, string] => Boolean(row[1]));

  if (!rows.length) return y;

  drawSectionLabel(doc, brand, "Bank", x, y);
  let cursorY = y + 32;
  doc.font("Helvetica").fontSize(8.8).fillColor(brand.text);
  for (const [label, value] of rows) {
    const text = `${label}: ${value}`;
    const lineHeight = doc.heightOfString(text, { width: 260, lineGap: 1 });
    doc.text(text, x, cursorY, { width: 260, lineGap: 1 });
    cursorY += lineHeight + 2;
  }
  return cursorY;
}

export async function generateInvoicePdf(invoiceId: string) {
  const invoice = await prisma.invoice.findUnique({
    where: { id: invoiceId },
    include: {
      buyerCompany: true,
      sellerCompany: true,
      purchaseOrder: true,
      lines: { include: { item: true } },
    },
  });
  if (!invoice) throw new Error("Invoice not found");
  const storageDir = path.resolve(process.cwd(), "storage", "invoices");
  fs.mkdirSync(storageDir, { recursive: true });

  const safeNumber = invoice.invoiceNumber.replace(/[^a-zA-Z0-9-_]/g, "_");
  const pdfPath = path.join(storageDir, `${safeNumber}.pdf`);

  await new Promise<void>((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 42 });
    const stream = fs.createWriteStream(pdfPath);
    doc.pipe(stream);
    const brand = getDocumentBrand(invoice.sellerCompany);

    drawBrandHeader(doc, brand, "TAX INVOICE", "Invoice No", invoice.invoiceNumber, "Date", invoice.createdAt.toLocaleDateString(), "PO Ref", invoice.purchaseOrder.poNumber);

    const top = 150;
    const sellerBottom = drawCompanyBlock(doc, brand, "Seller", invoice.sellerCompany, 42, top);
    const buyerBottom = drawCompanyBlock(doc, brand, "Buyer", invoice.buyerCompany, 330, top);

    const tableTop = Math.max(sellerBottom, buyerBottom, 238) + 18;
    drawTableHeader(doc, brand, tableTop);

    let y = tableTop + 34;
    doc.font("Helvetica").fontSize(9).fillColor(brand.text);
    for (const [index, line] of invoice.lines.entries()) {
      if (y > 700) {
        doc.addPage();
        drawBrandHeader(doc, brand, "TAX INVOICE", "Invoice No", invoice.invoiceNumber, "Date", invoice.createdAt.toLocaleDateString(), "PO Ref", invoice.purchaseOrder.poNumber);
        y = 145;
        drawTableHeader(doc, brand, y);
        y += 34;
      }
      if (index % 2 === 0) {
        doc.roundedRect(42, y - 6, 508, 22, 3).fill(brand.pale);
      }
      doc.fillColor(brand.text).font("Helvetica").fontSize(8.5);
      doc.text(`${line.item.sku} - ${line.item.name}`, 52, y, { width: 250, lineBreak: false });
      doc.fontSize(9);
      doc.text(String(line.quantity), 305, y, { width: 40, align: "right" });
      doc.text(money(line.unitPrice), 350, y, { width: 75, align: "right" });
      doc.text(`${Number(line.vatRate) * 100}%`, 430, y, { width: 40, align: "right" });
      doc.text(money(line.lineTotal), 475, y, { width: 65, align: "right" });
      y += 24;
    }

    y += 14;
    drawTotalsBox(doc, brand, y, [
      ["Subtotal", money(invoice.subtotal)],
      ["VAT 5%", money(invoice.vatAmount)],
      ["Total", money(invoice.total)],
    ]);

    drawBankDetails(doc, brand, invoice.sellerCompany, 42, y);

    doc.fillColor(brand.text).font("Helvetica").fontSize(9).text("Generated by B2B Business Portal. This PDF copy is stored for audit and email attachment use.", 42, 760, { width: 508 });

    doc.end();
    stream.on("finish", resolve);
    stream.on("error", reject);
  });

  return prisma.invoice.update({
    where: { id: invoiceId },
    data: { pdfPath },
    include: {
      buyerCompany: true,
      sellerCompany: true,
      purchaseOrder: true,
      lines: { include: { item: true } },
    },
  });
}

export async function getInvoicePdfFile(invoiceId: string) {
  let invoice = await prisma.invoice.findUnique({
    where: { id: invoiceId },
    include: {
      buyerCompany: true,
      sellerCompany: true,
      purchaseOrder: true,
      lines: { include: { item: true } },
    },
  });
  if (!invoice) throw new Error("Invoice not found");
  if (!invoice.pdfPath || !fs.existsSync(invoice.pdfPath)) {
    invoice = await generateInvoicePdf(invoiceId);
  }
  return {
    invoice,
    path: invoice.pdfPath!,
    filename: `${invoice.invoiceNumber}.pdf`,
  };
}
