import fs from "node:fs";
import path from "node:path";
import PDFDocument from "pdfkit";
import { prisma } from "../db";
import { drawBrandHeader, drawSectionLabel, drawTableHeader, drawTotalsBox, getDocumentBrand } from "./documentBrand";

function money(value: { toFixed(decimalPlaces: number): string } | string | number) {
  return `AED ${Number(value.toString()).toFixed(2)}`;
}

export async function getPurchaseOrderPdf(orderId: string) {
  const order = await prisma.purchaseOrder.findUnique({
    where: { id: orderId },
    include: {
      buyerCompany: true,
      sellerCompany: true,
      lines: { include: { item: true } },
    },
  });
  if (!order) throw new Error("Purchase order not found");

  return writePurchaseOrderPdf(order);
}

export async function getPurchaseOrderPdfForTarget(targetId: string) {
  const order = await prisma.purchaseOrder.findFirst({
    where: { quotation: { requirement: { targetId } } },
    include: {
      buyerCompany: true,
      sellerCompany: true,
      lines: { include: { item: true } },
    },
    orderBy: { createdAt: "desc" },
  });
  if (!order) throw new Error("Purchase order not found for target");

  return writePurchaseOrderPdf(order);
}

async function writePurchaseOrderPdf(order: {
  id: string;
  poNumber: string;
  createdAt: Date;
  subtotal: { toFixed(decimalPlaces: number): string };
  vatAmount: { toFixed(decimalPlaces: number): string };
  total: { toFixed(decimalPlaces: number): string };
  buyerCompany: { legalName: string; location: string; email: string; trn: string | null };
  sellerCompany: { legalName: string; location: string; email: string; trn: string | null };
  lines: Array<{
    quantity: number;
    unitPrice: { toFixed(decimalPlaces: number): string };
    vatRate: { toString(): string };
    lineTotal: { toFixed(decimalPlaces: number): string };
    item: { sku: string; name: string };
  }>;
}) {
  const storageDir = path.resolve(process.cwd(), "storage", "purchase-orders");
  fs.mkdirSync(storageDir, { recursive: true });
  const safeNumber = order.poNumber.replace(/[^a-zA-Z0-9-_]/g, "_");
  const pdfPath = path.join(storageDir, `${safeNumber}.pdf`);

  await new Promise<void>((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 42 });
    const stream = fs.createWriteStream(pdfPath);
    doc.pipe(stream);
    const brand = getDocumentBrand(order.buyerCompany);

    drawBrandHeader(doc, brand, "PURCHASE ORDER", "PO No", order.poNumber, "Date", order.createdAt.toLocaleDateString());

    const top = 150;
    drawSectionLabel(doc, brand, "Buyer", 42, top);
    doc.font("Helvetica").fontSize(10).fillColor(brand.text).text(order.buyerCompany.legalName, 42, top + 32, { width: 220 });
    doc.text(order.buyerCompany.location, { width: 220 });
    doc.text(`Email: ${order.buyerCompany.email}`, { width: 220 });
    doc.text(`TRN: ${order.buyerCompany.trn ?? "Not set"}`, { width: 220 });

    drawSectionLabel(doc, brand, "Vendor", 330, top);
    doc.font("Helvetica").fontSize(10).fillColor(brand.text).text(order.sellerCompany.legalName, 330, top + 32, { width: 220 });
    doc.text(order.sellerCompany.location, 330);
    doc.text(`Email: ${order.sellerCompany.email}`, 330);
    doc.text(`TRN: ${order.sellerCompany.trn ?? "Not set"}`, 330);

    const tableTop = Math.max(doc.y, 220);
    drawTableHeader(doc, brand, tableTop);

    let y = tableTop + 34;
    doc.font("Helvetica").fontSize(9).fillColor(brand.text);
    for (const [index, line] of order.lines.entries()) {
      if (y > 700) {
        doc.addPage();
        drawBrandHeader(doc, brand, "PURCHASE ORDER", "PO No", order.poNumber, "Date", order.createdAt.toLocaleDateString());
        y = 145;
        drawTableHeader(doc, brand, y);
        y += 34;
      }
      if (index % 2 === 0) {
        doc.roundedRect(42, y - 6, 508, 22, 3).fill(brand.pale);
      }
      doc.fillColor(brand.text).font("Helvetica").fontSize(8.5);
      doc.text(`${line.item.sku} - ${line.item.name}`, 52, y, { width: 250, lineBreak: false });
      doc.fontSize(9);
      doc.text(String(line.quantity), 305, y, { width: 40, align: "right" });
      doc.text(money(line.unitPrice), 350, y, { width: 75, align: "right" });
      doc.text(`${Number(line.vatRate) * 100}%`, 430, y, { width: 40, align: "right" });
      doc.text(money(line.lineTotal), 475, y, { width: 65, align: "right" });
      y += 24;
    }

    y += 14;
    drawTotalsBox(doc, brand, y, [
      ["Subtotal", money(order.subtotal)],
      ["VAT 5%", money(order.vatAmount)],
      ["Total", money(order.total)],
    ]);

    doc.fillColor(brand.text).font("Helvetica").fontSize(9).text("Generated by B2B Business Portal.", 42, 760, { width: 508 });

    doc.end();
    stream.on("finish", resolve);
    stream.on("error", reject);
  });

  return {
    order,
    path: pdfPath,
    filename: `${order.poNumber}.pdf`,
  };
}
